### ISSUE TITLE
Console Warning related to deprecated EventEmitter.removeListener method usage

### ISSUE THREAD

**Issue by Thanaen** [amrlabib/react-native-appstate-hook#11] opened 2021-08-18 13:27 UTC
Hello,

I've upgraded my project to React Native 0.65.0, and I am now getting this console warning:
![image](https://user-images.githubusercontent.com/16762369/129905662-67eb8687-9c6d-411b-98b5-bfcbc1a5e15b.png)

I've forked this project to try fixing this issue, but it seems harder than I expected. 🙁

I haven't made a reproduction repo, but I could make one if needed. 😄

**Comment by JuanpaG94** [comment] 2021-09-17 10:25
I'm having the same issue since RN 0.65.0.

I found this on React Native changelog. I think this project needs a refactor.
![imagen](https://user-images.githubusercontent.com/33027054/133768038-7d13363c-3398-4f33-8dd3-4af3d9bfa015.png)

**Comment by amrlabib** [comment] 2021-09-21 07:21
Hello, sorry for the late response and thank you for the PR @JuanpaG94. the issue is fixed in latest version 1.0.6

**Closed by amrlabib** 2021-09-21 07:21 UTC
